# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='quote_author',
        ),
    ]
