# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161115_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='quote_author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
